version: "3.8"
services:
  mcserver:
    image: minecraft-server
    expose:
      - 25565:25565
    ports:
      - 25565:25565
    volumes:
      - ./mounts/world:/mc/world
      - ./mounts/logs:/mc/logs
      - ./mounts/backups:/mc/backups